export const SETUP_USER_BEGIN = "SET_UP_USER";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";
export const HIDE_ALERT = "HIDE_ALERT";
export const SET_USER_REQUIREMENT = "SET_USER_REQUIREMENT";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_ALERT = "SET_ALERT";
export const SETUP_PROVIDER_BEGIN = "SETUP_PROVIDER_BEGIN";
export const SETUP_PROVIDER_SUCCESS = "SETUP_PROVIDER_SUCCESS";
export const SETUP_PROVIDER_ERROR = "SETUP_PROVIDER_ERROR";
export const LOGOUT_PROVIDER = "LOGOUT_PROVIDER";
export const SETUP_ADMIN_BEGIN = "SETUP_ADMIN_BEGIN";
export const SETUP_ADMIN_SUCCESS = "SETUP_ADMIN_SUCCESS";
export const SETUP_ADMIN_ERROR = "SETUP_ADMIN_ERROR";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
export const SUBSCRIBE_BEGIN = "SUBSCRIBE_BEGIN";
export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS";
export const SUBSCRIBE_ERROR = "SUBSCRIBE_ERROR";
export const SET_USER_SLA = "SET_USER_SLA";
export const UPDATE_RESOURCES_BEGIN = "UPDATE_RESOURCES_BEGIN";
export const UPDATE_RESOURCES_SUCCESS = "UPDATE_RESOURCES_SUCCESS";
export const UPDATE_RESOURCES_ERROR = "UPDATE_RESOURCES_ERROR";
export const UPDATE_PROVIDER_BEGIN = "UPDATE_PROVIDER_BEGIN";
export const UPDATE_PROVIDER_SUCCESS = "UPDATE_PROVIDER_SUCCESS";
export const UPDATE_PROVIDER_ERROR = "UPDATE_PROVIDER_ERROR";


